server:
  port: 8083

spring:
  application:
    name: homeease-notification-service

homeease:
  firebase:
    credentials-path: ${FIREBASE_CREDENTIALS_PATH:classpath:firebase-service-account.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
